---
apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-manager-config
  namespace: system
data:
  config.yaml: |
    routeToContourRatio: 1
    defaultTimeout:
      publicClass: 5s
      interDcClass: 5s
      defaultClass: 30s
